In [1]:

# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribución de las variables
# ------------------------------------------------------------------------------
import scipy.stats as stats
from scipy.stats import chi2_contingency, ttest_ind

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv("../files/marketing_AB.csv",index_col=0)
df.head()

   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

In [5]:
df['test group'].unique()

array(['ad', 'psa'], dtype=object)

In [6]:
df.columns

Index(['user id', 'test group', 'converted', 'total ads', 'most ads day',
       'most ads hour'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 588101 entries, 0 to 588100
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user id        588101 non-null  int64
 1   test group     588101 non-null  object
 2   converted      588101 non-null  bool
 3   total ads      588101 non-null  int64
 4   most ads day   588101 non-null  object
 5   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(3), object(2)
memory usage: 27.5+ MB

In [8]:
df.isnull().sum()

user id          0
test group       0
converted        0
total ads        0
most ads day     0
most ads hour    0
dtype: int64

In [10]:
df.describe()

            user id      total ads  most ads hour
count  5.881010e+05  588101.000000  588101.000000
mean   1.310692e+06      24.820876      14.469061
std    2.022260e+05      43.715181       4.834634
min    9.000000e+05       1.000000       0.000000
25%    1.143190e+06       4.000000      11.000000
50%    1.313725e+06      13.000000      14.000000
75%    1.484088e+06      27.000000      18.000000
max    1.654483e+06    2065.000000      23.000000

In [13]:
'''Definición de las hipótesis: Plantea una hipótesis nula (H0) y una hipótesis alternativa (H1) para el experimento (en este caso os las damos definidas):
- Hipótesis nula (H0): No hay diferencia significativa en la tasa de conversión entre los grupos de prueba "ad" y "psa".
- Hipótesis alternativa (H1): Existe una diferencia significativa en la tasa de conversión entre los grupos de prueba "ad" y "psa".'''
df['CR'] = df[df['converted'] == True].count()/df['user id'].count()
df.head()

   user id test group  converted  total ads most ads day  most ads hour  CR
0  1069124         ad      False        130       Monday             20 NaN
1  1119715         ad      False         93      Tuesday             22 NaN
2  1144181         ad      False         21      Tuesday             18 NaN
3  1435133         ad      False        355      Tuesday             10 NaN
4  1015700         ad      False        276       Friday             14 NaN

In [14]:
((df[df['converted']=True])/(df['user id'].count()))*100

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (3482277746.py, line 1)

In [16]:
total_id =df['user id'].count()

In [18]:
converted =df['converted']==True

In [19]:
(converted/total_id)*100

0         0.00017
1         0.00017
2         0.00017
3         0.00017
4         0.00017
           ...
588096    0.00017
588097    0.00017
588098    0.00017
588099    0.00017
588100    0.00017
Name: converted, Length: 588101, dtype: float64