In [3]:
import pandas as pd 
import numpy as np

In [4]:
df1 = pd.read_csv("../files/rating-and-performance.csv")
df2 = pd.read_csv("../files/insight.csv")

In [5]:
df3 = df1(df2, left_on='title', right_on = "title_orig")
df3.head()

TypeError: 'DataFrame' object is not callable

In [6]:
df3 = df1.merge(df2, on="id", how="left")

KeyError: 'id'

In [ ]:
#1. Unid los dos DataFrames en uno solo, usando el método que considereis más correcto. 
# Querremos quedarnos con todos los productos que estén en los dos conjuntos de datos.
df3 = pd.concat([df1,df2], axis =0, ignore_index=True)

In [ ]:
df3.head()

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,...,total.units.sold,mean.units.sold.per.product,merchant.ratings.count,mean.product.prices,mean.retail.prices,average.discount,mean.discount,mean.product.ratings.count,total.urgency.count,urgency.text.rate
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14.0,EUR,100.0,0.0,3.76,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22.0,EUR,20000.0,1.0,3.45,6135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43.0,EUR,100.0,0.0,3.57,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8.0,EUR,5000.0,1.0,4.03,579.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3.0,EUR,100.0,1.0,3.10,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#2.Explorad el nombre de las columnas, ¿hay alguna que esté repetida o que no nos aporte información de valor?
df3.drop(["title", "mean.product.prices","mean.discount"], axis = 1, inplace = True)

In [ ]:
df3.head(2)

,index,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant.id,listed.products,total.units.sold,mean.units.sold.per.product,merchant.ratings.count,mean.retail.prices,average.discount,mean.product.ratings.count,total.urgency.count,urgency.text.rate
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14.0,EUR,100.0,0.0,3.76,54.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22.0,EUR,20000.0,1.0,3.45,6135.0,2269.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# ¿Hay alguna columna que solo tenga un valor? En caso de ser así, eliminadlas. 
#df3["currency_buyer"].value_counts()
columnas_un_valor = []
for column in df3.columns:
    if df3[column].value_counts().shape[0] == 1:
        columnas_un_valor.append(column)
        
df3.drop(columnas_un_valor, axis=1)

,index,title_orig,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,...,merchant.id,listed.products,total.units.sold,mean.units.sold.per.product,merchant.ratings.count,mean.retail.prices,average.discount,mean.product.ratings.count,total.urgency.count,urgency.text.rate
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14.0,100.0,0.0,3.760,54.0,26.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22.0,20000.0,1.0,3.450,6135.0,2269.0,1027.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020 New Arrival Women Spring and Summer Beach...,8.00,43.0,100.0,0.0,3.570,14.0,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8.0,5000.0,1.0,4.030,579.0,295.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3.0,100.0,1.0,3.100,20.0,6.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2526,953,NaN,NaN,NaN,NaN,NaN,3.999,NaN,NaN,NaN,...,567bad8582c35f28103e5813,1.0,2.0,2.0,21307.0,10.0,-10.0,1.0,NaN,NaN
2527,954,NaN,NaN,NaN,NaN,NaN,4.303,NaN,NaN,NaN,...,5b24edf0d1c360301099e9c6,1.0,2.0,2.0,693.0,16.0,0.0,0.0,NaN,NaN
2528,955,NaN,NaN,NaN,NaN,NaN,3.598,NaN,NaN,NaN,...,5d417e7070327a2743021677,1.0,1.0,1.0,378.0,9.0,70.0,0.0,NaN,NaN
2529,956,NaN,NaN,NaN,NaN,NaN,3.956,NaN,NaN,NaN,...,5add589edb5f1f32114d07df,1.0,1.0,1.0,1134.0,14.0,0.0,0.0,NaN,NaN
2530,957,NaN,NaN,NaN,NaN,NaN,4.007,NaN,NaN,NaN,...,5d4b8931933fb13f8a1fe232,1.0,1.0,1.0,1380.0,30.0,64.0,0.0,NaN,NaN

In [ ]:
#3.Algunas de las columnas tienen . en sus nombres y en otras tenemos _. 
# Unifica el nombre de las columnas para que todas tengan "_". Además, todas deben estar en minúsculas.
col_nuevas = {col : col.lower().replace(".", "_") for col in df3.columns}
df3.rename(columns= col_nuevas, inplace = True)

NameError: name 'df3' is not defined

In [ ]:
#4.En la columna de merchant_info_subtitle, si nos fijamos hay algunas celdas donde tenemos entre paréntesis el número 
#total de calificaciones para el comerciante (que es la misma información que la que tenemos en la columna "merchant_rating_count"). 
# Eliminad de la columna "merchant_info_subtitle" la parte del string de los paréntesis. Guardar el resultado de vuestra limpieza 
# en una columna que se llame igual, es decir, "merchant_info_subtitle".