In [1]:
import pandas as pd
import numpy as np 

pd.set_option('display.max_columns',None)

In [ ]:
#1.Total de unidades vendidas por país de origen del vendedor. 
# Debéis agrupar los datos según el país de origen del vendedor y calcular el total de unidades vendidas para cada país. 
# Esto nos dará una idea de qué países tienen una mayor participación en las ventas totales y cuáles tienen menos. 
# Devuelve los resultados en un DataFrame ordenados de mayor a menor en función de la cantidad de unidades vendidas.

In [2]:
df = pd.read_csv("../files/merchant_fill.csv")

In [32]:
df.head()

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,0,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,-14.0,-14.00,54.0
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,0,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.90,8,1000,1,3.83,99,43.0,18.0,23.0,8.0,7.0,0,0,0,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,0,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
3,3,Summer Women s Fashion Lace Up Tie Pants Plus...,4.93,6,100,0,3.77,47,22.0,7.0,8.0,5.0,5.0,0,0,0,"Summer,Shorts,Lace,pants,Waist,Short pants,Yel...",red,S,Standard Shipping,1,0,41,50,CN,sarahouse,83% Positive Feedback,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5d58daef3159a812b05933d2,5d58daef3159a812b05933d2,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
4,4,Nouvelle mode d'été femmes robe décontractée c...,5.65,10,100,1,2.86,7,1.0,1.0,2.0,2.0,1.0,0,0,0,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,XXS,Livraison standard,1,0,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5e9fa7de39682a0043ab7898,5e9fa7de39682a0043ab7898,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0

In [5]:
df.columns

Index(['Unnamed: 0', 'title', 'price', 'retail_price', 'units_sold',
       'uses_ad_boosts', 'rating_sold', 'rating_count', 'rating_five_count',
       'rating_four_count', 'rating_three_count', 'rating_two_count',
       'rating_one_count', 'badge_local_product', 'badge_product_quality',
       'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'origin_country', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'product_url', 'product_id', 'listed_products',
       'total_units_sold', 'mean_units_sold_per_product', 'rating_employee',
       'merchant_ratings_count', 'mean_product_prices', 'mean_retail_prices',
       'average_discount', 'mean_discount', 'mean_product_ratings_count'],
      dtype='object')

In [13]:
# pais origen de vendedor origin_country
# ventas totales total_units_sold


df_grouped = df.groupby('origin_country')['total_units_sold'].sum().reset_index()

In [24]:
df_grouped_sorted = df_grouped.sort_values(by='total_units_sold', ascending=False).reset_index(drop=True)

In [25]:
df_grouped_sorted

  origin_country  total_units_sold
0             CN          17371643
1             US             60460
2             SG             40200
3             GB              1000
4             VE               650
5             AT               100

In [29]:
#2.Estadísticas de precio por país de envío. Vamos a explorar el precio promedio y el precio máximo de los productos según 
# el país al que se envían. Al hacer esto, podremos entender cómo varían los precios según el destino del envío y si hay 
# alguna tendencia interesante que valga la pena analizar. Devuelve los resultados en un DataFrame.

df_promedio_maximo = df.groupby('origin_country')['price'].agg(['mean' , 'max'])

In [30]:
df_promedio_maximo

                    mean    max
origin_country
AT              7.000000   7.00
CN              8.341629  49.00
GB              9.000000   9.00
SG              3.380000   3.93
US              9.397097  16.00
VE              8.298000  16.00

In [42]:
#3.Conteo de productos con y sin distintivo de producto local. 
# Vamos a clasificar los productos según si tienen o no un distintivo de producto local. 
# Luego, calcularemos el conteo de productos en cada categoría para comprender cuántos productos tienen este distintivo y cuántos no. 
# Esto puede proporcionarnos información sobre cómo se promocionan los productos con esta característica. 
# Devuelve los resultados en un DataFrame.

#'badge_local_product'

df['badge_local_product'] = df['badge_local_product'].map({0 :"NO",1:"Si"})
df.head(3)

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,NaN,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,0,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,-14.0,-14.00,54.0
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.0,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,NaN,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,0,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.9,8,1000,1,3.83,99,43.0,18.0,23.0,8.0,7.0,NaN,0,0,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,0,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0

In [31]:
df.columns

Index(['Unnamed: 0', 'title', 'price', 'retail_price', 'units_sold',
       'uses_ad_boosts', 'rating_sold', 'rating_count', 'rating_five_count',
       'rating_four_count', 'rating_three_count', 'rating_two_count',
       'rating_one_count', 'badge_local_product', 'badge_product_quality',
       'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'origin_country', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'product_url', 'product_id', 'listed_products',
       'total_units_sold', 'mean_units_sold_per_product', 'rating_employee',
       'merchant_ratings_count', 'mean_product_prices', 'mean_retail_prices',
       'average_discount', 'mean_discount', 'mean_product_ratings_count'],
      dtype='object')

In [35]:
df_total_local_product = df.groupby(['badge_local_product'])['product_id'].count().reset_index()

In [36]:
df_total_local_product

  badge_local_product  product_id
0                  NO        1544
1                  Si          29

In [39]:
#4. Promedio de unidades vendidas por tipo de envío. 
# Nuestro objetivo es analizar cómo se correlaciona el tipo de envío (columna shipping_option_name ) con las unidades vendidas. 
# Vamos a calcular el promedio de unidades vendidas para cada tipo de opción de envío. 
# Esto podría ayudarnos a determinar si ciertos métodos de envío están relacionados con un mayor o menor rendimiento en las ventas. 
# Devuelve los resultados en un DataFrame. ¿Qué conclusiones puedes sacar de este resultado?
#units_sold
#df_unidades_vendidas = df.groupby([]).mean().reset_index()
df.groupby(["units_sold","shipping_option_name"]).mean(numeric_only= True)

                                     Unnamed: 0      price  retail_price  \
units_sold shipping_option_name
1          Livraison standard        840.666667   9.240000     17.666667
2          Livraison standard        888.500000  13.500000     13.000000
3          Livraison standard       1005.000000   9.905000     22.500000
6          Livraison standard        690.000000   6.000000     17.000000
7          Livraison standard        805.500000   8.000000     32.000000
8          Livraison standard       1164.500000   7.750000     58.750000
10         Livraison standard        821.653061   8.443878     33.000000
50         Livraison standard        743.573333   7.598267     19.613333
           Standard Shipping        1562.000000  27.000000     23.000000
100        Envio Padrão              888.750000   8.905000     28.000000
           Envío normal              629.000000   8.000000      7.000000
           Expediere Standard        439.000000   9.330000      8.500000
           Livraison Express        1071.000000  28.500000     24.500000
           Livraison standard        787.256198   7.971612     22.915289
           Spedizione standard      1185.000000   5.000000     26.000000
           Standard Shipping         534.200000   5.972000      6.800000
           Standardowa wysyłka       953.000000  16.000000     18.000000
           Standardversand           403.333333   7.906667     13.000000
           Стандартная доставка     1517.000000   9.000000      8.000000
           الشحن القياسي            1060.666667  11.333333     45.666667
1000       Envio Padrão              574.500000  10.455000     11.500000
           Envío normal             1500.000000   5.000000      5.000000
           Expediere Standard       1108.500000  13.500000     22.000000
           Livraison Express        1177.000000  16.000000     14.000000
           Livraison standard        816.884021   8.520541     24.744845
           Spedizione standard      1274.000000   8.000000     38.000000
           Standard Shipping        1087.500000   9.590000     31.250000
           Standart Gönderi          443.000000  11.000000     10.000000
           الشحن القياسي             779.000000   7.000000     50.000000
5000       Envio Padrão              384.500000   7.850000     34.500000
           Envío normal              179.333333   8.333333      7.333333
           Livraison standard        780.000000   8.511990     20.640777
           Standard Shipping         802.500000  10.500000     33.500000
           Стандартная доставка       35.500000   9.000000      8.000000
           การส่งสินค้ามาตรฐาน       167.000000   3.830000      4.000000
10000      Ekspresowa wysyłka       1322.000000   6.000000      6.000000
           Envio Padrão             1075.000000   6.000000     17.000000
           Livraison standard        750.278107   8.341243     21.183432
           Standard Shipping         328.333333   7.666667      9.000000
           Standardowa wysyłka       205.000000   5.830000      5.000000
           Standart Gönderi           98.000000   9.000000      8.000000
           ការដឹកជញ្ជូនតាមស្តង់ដារ   859.000000  12.000000     13.000000
20000      Livraison standard        771.740000   8.773700     27.240000
           Standard Shipping         858.500000   8.000000     21.000000
           Standardowa wysyłka       222.000000   5.780000      8.000000
50000      Livraison standard        770.411765   6.962353     27.882353
100000     Livraison standard        658.166667   6.073333     25.666667

                                    uses_ad_boosts  rating_sold  rating_count  \
units_sold shipping_option_name
1          Livraison standard             0.000000     5.000000      0.000000
2          Livraison standard             0.000000     3.500000      0.500000
3          Livraison standard             0.000000     5.000000      0.000000
6          Livraison standard             0.000000     5.000000      0.000000
7          Livraison standard             0.000000     5.000000      0.500000
8          Livraison standard             0.000000     5.000000      0.000000
10         Livraison standard             0.244898     4.182653      1.897959
50         Livraison standard             0.333333     3.873467      5.226667
           Standard Shipping              1.000000     4.250000     12.000000
100        Envio Padrão                   0.500000     4.367500     47.250000
           Envío normal                   0.000000     4.390000    111.000000
           Expediere Standard             0.500000     3.540000      8.500000
           Livraison Express              0.000000     3.730000     10.000000
           Livraison standard             0.485537     3.714029     33.671488
           Spedizione standard            1.000000     4.000000      4.000000
           Standard Shipping              0.400000     4.186000     23.200000
           Standardowa wysyłka            0.000000     3.880000     69.000000
           Standardversand                0.666667     3.133333     18.333333
           Стандартная доставка           0.000000     4.500000      8.000000
           الشحن القياسي                  0.000000     4.123333     24.333333
1000       Envio Padrão                   1.000000     3.425000    198.000000
           Envío normal                   0.000000     3.850000    279.000000
           Expediere Standard             0.000000     4.140000    310.500000
           Livraison Express              1.000000     4.520000    552.000000
           Livraison standard             0.458763     3.798866    281.824742
           Spedizione standard            0.000000     4.140000    196.000000
           Standard Shipping              0.625000     3.947500    182.625000
           Standart Gönderi               0.000000     3.670000    215.000000
           الشحن القياسي                  1.000000     4.080000    408.000000
5000       Envio Padrão                   0.500000     3.290000    634.500000
           Envío normal                   0.333333     4.210000    849.666667
           Livraison standard             0.393204     3.829466    878.466019
           Standard Shipping              0.000000     3.470000    482.000000
           Стандартная доставка           0.000000     3.680000    856.000000
           การส่งสินค้ามาตรฐาน            0.000000     3.290000    931.500000
10000      Ekspresowa wysyłka             0.000000     4.290000   2808.000000
           Envio Padrão                   0.000000     4.350000   3279.000000
           Livraison standard             0.426036     3.901302   1870.615385
           Standard Shipping              0.000000     3.400000   1526.333333
           Standardowa wysyłka            1.000000     4.220000   2055.000000
           Standart Gönderi               0.000000     3.800000   1231.000000
           ការដឹកជញ្ជូនតាមស្តង់ដារ        0.000000     3.560000    893.000000
20000      Livraison standard             0.470000     3.863100   4610.750000
           Standard Shipping              0.500000     4.045000   3404.500000
           Standardowa wysyłka            1.000000     4.000000   3975.000000
50000      Livraison standard             0.235294     3.903529  10731.941176
100000     Livraison standard             0.500000     3.836667  15646.833333

                                    rating_five_count  rating_four_count  \
units_sold shipping_option_name
1          Livraison standard                     NaN                NaN
2          Livraison standard                0.000000           0.000000
3          Livraison standard                     NaN                NaN
6          Livraison standard                     NaN                NaN
7          Livraison standard                1.000000           0.000000
8          Livraison standard                     NaN                NaN
10         Livraison standard                1.241379           0.689655
50         Livraison standard                2.816901           1.042254
           Standard Shipping                 7.000000           2.000000
100        Envio Padrão                     42.500000          18.000000
           Envío normal                     77.000000          14.000000
           Expediere Standard                3.000000           1.500000
           Livraison Express                 4.500000           1.500000
           Livraison standard               15.566038           6.563941
           Spedizione standard               3.000000           0.000000
           Standard Shipping                10.600000           4.000000
           Standardowa wysyłka              33.000000          15.000000
           Standardversand                   6.000000           4.000000
           Стандартная доставка              6.000000           0.000000
           الشحن القياسي                    11.666667           7.666667
1000       Envio Padrão                     72.500000          36.500000
           Envío normal                    133.000000          59.000000
           Expediere Standard              177.500000          57.000000
           Livraison Express               394.000000          97.000000
           Livraison standard              134.247423          54.059278
           Spedizione standard             113.000000          35.000000
           Standard Shipping                93.000000          38.375000
           Standart Gönderi                 94.000000          32.000000
           الشحن القياسي                   212.000000          89.000000
5000       Envio Padrão                    244.000000          85.500000
           Envío normal                    503.333333         157.333333
           Livraison standard              421.262136         168.364078
           Standard Shipping               185.000000          80.500000
           Стандартная доставка            358.000000         169.000000
           การส่งสินค้ามาตรฐาน             297.500000         149.500000
10000      Ekspresowa wysyłka             1789.000000         459.000000
           Envio Padrão                   2091.000000         612.000000
           Livraison standard              930.514793         370.142012
           Standard Shipping               555.333333         307.666667
           Standardowa wysyłka            1162.000000         488.000000
           Standart Gönderi                555.000000         240.000000
           ការដឹកជញ្ជូនតាមស្តង់ដារ         364.000000         140.000000
20000      Livraison standard             2206.490000         911.300000
           Standard Shipping              1823.500000         670.500000
           Standardowa wysyłka            2054.000000         774.000000
50000      Livraison standard             5216.764706        2104.882353
100000     Livraison standard             7187.166667        3120.500000

                                    rating_three_count  rating_two_count  \
units_sold shipping_option_name
1          Livraison standard                      NaN               NaN
2          Livraison standard                 0.000000          1.000000
3          Livraison standard                      NaN               NaN
6          Livraison standard                      NaN               NaN
7          Livraison standard                 0.000000          0.000000
8          Livraison standard                      NaN               NaN
10         Livraison standard                 0.379310          0.379310
50         Livraison standard                 0.633803          0.450704
           Standard Shipping                  2.000000          1.000000
100        Envio Padrão                      15.000000          9.000000
           Envío normal                      10.000000          6.000000
           Expediere Standard                 1.500000          0.000000
           Livraison Express                  0.000000          1.000000
           Livraison standard                 4.857442          2.465409
           Spedizione standard                0.000000          0.000000
           Standard Shipping                  3.400000          2.600000
           Standardowa wysyłka               10.000000          2.000000
           Standardversand                    2.333333          2.666667
           Стандартная доставка               2.000000          0.000000
           الشحن القياسي                      2.333333          1.000000
1000       Envio Padrão                      30.500000         18.500000
           Envío normal                      32.000000         23.000000
           Expediere Standard                34.500000         15.000000
           Livraison Express                 33.000000          9.000000
           Livraison standard                40.121134         19.525773
           Spedizione standard               25.000000          8.000000
           Standard Shipping                 25.000000          8.750000
           Standart Gönderi                  40.000000         23.000000
           الشحن القياسي                     56.000000         29.000000
5000       Envio Padrão                     101.000000         53.000000
           Envío normal                     100.000000         38.666667
           Livraison standard               126.300971         61.587379
           Standard Shipping                 82.000000         46.500000
           Стандартная доставка             147.000000         64.000000
           การส่งสินค้ามาตรฐาน              183.000000        115.000000
10000      Ekspresowa wysyłka               300.000000        110.000000
           Envio Padrão                     336.000000        109.000000
           Livraison standard               263.059172        121.485207
           Standard Shipping                251.000000        153.333333
           Standardowa wysyłka              212.000000         83.000000
           Standart Gönderi                 211.000000         87.000000
           ការដឹកជញ្ជូនតាមស្តង់ដារ          157.000000         92.000000
20000      Livraison standard               688.470000        325.620000
           Standard Shipping                456.000000        193.500000
           Standardowa wysyłka              576.000000        242.000000
50000      Livraison standard              1614.058824        762.352941
100000     Livraison standard              2583.500000       1215.000000

                                    rating_one_count  badge_product_quality  \
units_sold shipping_option_name
1          Livraison standard                    NaN               0.000000
2          Livraison standard               0.000000               0.000000
3          Livraison standard                    NaN               0.000000
6          Livraison standard                    NaN               0.000000
7          Livraison standard               0.000000               0.000000
8          Livraison standard                    NaN               0.000000
10         Livraison standard               0.517241               0.000000
50         Livraison standard               0.577465               0.000000
           Standard Shipping                0.000000               0.000000
100        Envio Padrão                    10.000000               0.000000
           Envío normal                     4.000000               1.000000
           Expediere Standard               2.500000               0.000000
           Livraison Express                3.000000               0.000000
           Livraison standard               4.712788               0.051653
           Spedizione standard              1.000000               0.000000
           Standard Shipping                2.600000               0.000000
           Standardowa wysyłka              9.000000               0.000000
           Standardversand                  3.333333               0.000000
           Стандартная доставка             0.000000               0.000000
           الشحن القياسي                    1.666667               0.000000
1000       Envio Padrão                    40.000000               0.000000
           Envío normal                    32.000000               0.000000
           Expediere Standard              26.500000               0.500000
           Livraison Express               19.000000               1.000000
           Livraison standard              33.871134               0.074742
           Spedizione standard             15.000000               0.000000
           Standard Shipping               17.500000               0.375000
           Standart Gönderi                26.000000               0.000000
           الشحن القياسي                   22.000000               0.000000
5000       Envio Padrão                   151.000000               0.000000
           Envío normal                    50.333333               0.666667
           Livraison standard             100.951456               0.082524
           Standard Shipping               88.000000               0.000000
           Стандартная доставка           118.000000               0.000000
           การส่งสินค้ามาตรฐาน            186.500000               0.000000
10000      Ekspresowa wysyłka             150.000000               1.000000
           Envio Padrão                   131.000000               1.000000
           Livraison standard             185.414201               0.124260
           Standard Shipping              259.000000               0.000000
           Standardowa wysyłka            110.000000               0.000000
           Standart Gönderi               138.000000               0.000000
           ការដឹកជញ្ជូនតាមស្តង់ដារ        140.000000               0.000000
20000      Livraison standard             478.870000               0.120000
           Standard Shipping              261.000000               0.000000
           Standardowa wysyłka            329.000000               0.000000
50000      Livraison standard            1033.882353               0.176471
100000     Livraison standard            1540.666667               0.000000

                                    badge_fast_shipping  \
units_sold shipping_option_name
1          Livraison standard                  0.000000
2          Livraison standard                  0.000000
3          Livraison standard                  0.000000
6          Livraison standard                  0.000000
7          Livraison standard                  0.000000
8          Livraison standard                  0.000000
10         Livraison standard                  0.000000
50         Livraison standard                  0.000000
           Standard Shipping                   0.000000
100        Envio Padrão                        0.000000
           Envío normal                        0.000000
           Expediere Standard                  0.000000
           Livraison Express                   1.000000
           Livraison standard                  0.022727
           Spedizione standard                 0.000000
           Standard Shipping                   0.000000
           Standardowa wysyłka                 0.000000
           Standardversand                     0.000000
           Стандартная доставка                0.000000
           الشحن القياسي                       0.000000
1000       Envio Padrão                        0.000000
           Envío normal                        0.000000
           Expediere Standard                  0.000000
           Livraison Express                   1.000000
           Livraison standard                  0.007732
           Spedizione standard                 0.000000
           Standard Shipping                   0.000000
           Standart Gönderi                    0.000000
           الشحن القياسي                       0.000000
5000       Envio Padrão                        0.000000
           Envío normal                        0.000000
           Livraison standard                  0.000000

In [46]:
#5.Reemplazo de valores. A lo largo del DataFrame tenemos algunas columnas cuyos valores son cero y uno, 
# lo que podría llevar a confusión en su interpretación. Estas columnas son:
column_to_replace = ['uses_ad_boosts','badge_local_product','badge_product_quality','badge_fast_shipping','shipping_is_express']
df[column_to_replace] = df[column_to_replace].replace({0:"NO",1:"Si"})
df.head()

C:\Users\Luzma\AppData\Local\Temp\ipykernel_24088\3544948773.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column_to_replace] = df[column_to_replace].replace({0:"NO",1:"Si"})

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,100,NO,3.76,54,26.0,8.0,10.0,1.0,9.0,NaN,NO,NO,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,NO,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,-14.0,-14.00,54.0
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.00,22,20000,Si,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,NaN,NO,NO,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.90,8,1000,Si,3.83,99,43.0,18.0,23.0,8.0,7.0,NaN,NO,NO,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
3,3,Summer Women s Fashion Lace Up Tie Pants Plus...,4.93,6,100,NO,3.77,47,22.0,7.0,8.0,5.0,5.0,NaN,NO,NO,"Summer,Shorts,Lace,pants,Waist,Short pants,Yel...",red,S,Standard Shipping,1,NO,41,50,CN,sarahouse,83% Positive Feedback,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5d58daef3159a812b05933d2,5d58daef3159a812b05933d2,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
4,4,Nouvelle mode d'été femmes robe décontractée c...,5.65,10,100,Si,2.86,7,1.0,1.0,2.0,2.0,1.0,NaN,NO,NO,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5e9fa7de39682a0043ab7898,5e9fa7de39682a0043ab7898,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0

In [49]:
#6.Calificación de la calidad del producto. Sobreescribe la columna badge_product_quality utilizando apply() 
# para asignar "Buena" a las filas donde 'badge_product_quality' sea "No" y "Excelente" donde sea "Si".
def quality(num):
    if num == "NO":
        return "Buena"
    elif num == "Si":
        return "Excelente"
    else:
        return "No info"

df['badge_product_quality']= df['badge_product_quality'].apply(quality)

df.head()

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,average_discount,mean_discount,mean_product_ratings_count
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,100,NO,3.76,54,26.0,8.0,10.0,1.0,9.0,NaN,No info,NO,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,NO,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,-14.0,-14.00,54.0
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.00,22,20000,Si,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,NaN,No info,NO,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.90,8,1000,Si,3.83,99,43.0,18.0,23.0,8.0,7.0,NaN,No info,NO,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
3,3,Summer Women s Fashion Lace Up Tie Pants Plus...,4.93,6,100,NO,3.77,47,22.0,7.0,8.0,5.0,5.0,NaN,No info,NO,"Summer,Shorts,Lace,pants,Waist,Short pants,Yel...",red,S,Standard Shipping,1,NO,41,50,CN,sarahouse,83% Positive Feedback,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5d58daef3159a812b05933d2,5d58daef3159a812b05933d2,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0
4,4,Nouvelle mode d'été femmes robe décontractée c...,5.65,10,100,Si,2.86,7,1.0,1.0,2.0,2.0,1.0,NaN,No info,NO,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5e9fa7de39682a0043ab7898,5e9fa7de39682a0043ab7898,6,21400,3567.0,3.900,17752.0,5.68,10.33,38.0,37.83,1057.0

In [50]:
#7.Cálculo de descuento. Crea una nueva columna discount_percentage utilizando apply() que calcule el porcentaje de descuento basado 
# en las columnas 'price' y 'retail_price', redondea los decimales a 2. Después elimina las columnas de average_discount y mean_discount
df['discount_percentage'] = df.apply(lambda row: round((1 - row['price'] / row['retail_price']) * 100, 2), axis=1)

In [51]:
# Eliminar las columnas average_discount y mean_discount 
df.drop(['average_discount', 'mean_discount'], axis=1, inplace=True)

In [52]:
df.head()

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,mean_product_ratings_count,discount_percentage
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,100,NO,3.76,54,26.0,8.0,10.0,1.0,9.0,NaN,No info,NO,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,NO,34,50,CN,zgrdejia,NaN,568,4.128521,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,54.0,-14.29
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.00,22,20000,Si,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,NaN,No info,NO,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,63.64
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.90,8,1000,Si,3.83,99,43.0,18.0,23.0,8.0,7.0,NaN,No info,NO,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,38.75
3,3,Summer Women s Fashion Lace Up Tie Pants Plus...,4.93,6,100,NO,3.77,47,22.0,7.0,8.0,5.0,5.0,NaN,No info,NO,"Summer,Shorts,Lace,pants,Waist,Short pants,Yel...",red,S,Standard Shipping,1,NO,41,50,CN,sarahouse,83% Positive Feedback,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5d58daef3159a812b05933d2,5d58daef3159a812b05933d2,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,17.83
4,4,Nouvelle mode d'été femmes robe décontractée c...,5.65,10,100,Si,2.86,7,1.0,1.0,2.0,2.0,1.0,NaN,No info,NO,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,3.899673,56458aa03a698c35c9050988,https://www.wish.com/c/5e9fa7de39682a0043ab7898,5e9fa7de39682a0043ab7898,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,43.50

In [53]:
df.columns

Index(['Unnamed: 0', 'title', 'price', 'retail_price', 'units_sold',
       'uses_ad_boosts', 'rating_sold', 'rating_count', 'rating_five_count',
       'rating_four_count', 'rating_three_count', 'rating_two_count',
       'rating_one_count', 'badge_local_product', 'badge_product_quality',
       'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'origin_country', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'product_url', 'product_id', 'listed_products',
       'total_units_sold', 'mean_units_sold_per_product', 'rating_employee',
       'merchant_ratings_count', 'mean_product_prices', 'mean_retail_prices',
       'mean_product_ratings_count', 'discount_percentage'],
      dtype='object')

In [55]:
#8. Evaluación de la valoración del vendedor. Utiliza apply() para crear una nueva columna 
# 'seller_reputation' donde los valores sean "Buena" si 'merchant_rating' es mayor o igual a 4, y "Regular" si es menor a 4. 
# Después elimina la columna merchant_rating.
df['seller_reputation'] = df.apply(lambda row: 'Buena' if row['merchant_rating'] >= 4 else 'Regular', axis=1)
# Eliminar la columna 'merchant_rating' 
df.drop('merchant_rating', axis=1, inplace=True)

In [56]:
df.head(3)

,Unnamed: 0,title,price,retail_price,units_sold,uses_ad_boosts,rating_sold,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,origin_country,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_id,product_url,product_id,listed_products,total_units_sold,mean_units_sold_per_product,rating_employee,merchant_ratings_count,mean_product_prices,mean_retail_prices,mean_product_ratings_count,discount_percentage,seller_reputation
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,100,NO,3.76,54,26.0,8.0,10.0,1.0,9.0,NaN,No info,NO,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,Livraison standard,4,NO,34,50,CN,zgrdejia,NaN,568,595097d6a26f6e070cb878d1,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,5e9ae51d43d6a96e303acdb0,1,100,100.0,4.129,568.0,16.00,14.00,54.0,-14.29,Buena
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,8.0,22,20000,Si,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,NaN,No info,NO,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,Livraison standard,2,NO,41,50,CN,sarahouse,83 % avis positifs,17752,56458aa03a698c35c9050988,https://www.wish.com/c/58940d436a0d3d5da4e95a38,58940d436a0d3d5da4e95a38,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,63.64,Regular
2,2,Nouvelle mode d'été femmes robe décontractée c...,4.9,8,1000,Si,3.83,99,43.0,18.0,23.0,8.0,7.0,NaN,No info,NO,"Summer,Fashion,Necks,Beach,Dress,Loose,beach d...",white,XXS,Livraison standard,1,NO,41,50,CN,sarahouse,83 % avis positifs,17752,56458aa03a698c35c9050988,https://www.wish.com/c/5df2576d68963c1660471f9a,5df2576d68963c1660471f9a,6,21400,3567.0,3.900,17752.0,5.68,10.33,1057.0,38.75,Regular