In [1]:
import pandas as pd 
import numpy as np

In [12]:
#Leer los archivos CSV (ventas.csv, productos.csv, clientes.csv).
df_ventas = pd.read_csv("../files/ventas.csv")
df_ventas.head()

   ID_Cliente ID_Producto Fecha_Venta  Cantidad  Total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98

In [16]:
df_ventas.isnull().sum()

ID_Cliente     0
ID_Producto    0
Fecha_Venta    0
Cantidad       0
Total          0
dtype: int64

In [11]:
df_productos = pd.read_csv("../files/productos.csv",on_bad_lines='skip')
df_productos.head()

,ID,Nombre_Producto,Categoría,Precio,Origen,Descripción
A1,Pizza Margherita,Platos Preparados,8.99,Italia,Clásica pizza italiana con tomate,mozzarella fresca y albahaca.
B2,Risotto de Champiñones,Platos Preparados,6.75,Italia,Risotto cremoso con champiñones frescos,una delicia italiana para disfrutar en casa.
C3,Tiramisú,Postres,5.49,Italia,Postre clásico italiano con capas de bizcocho ...,mascarpone y cacao en polvo.
D4,Panettone,Repostería,10.99,Italia,Pan dulce navideño italiano con frutas confita...,un regalo tradicional en Italia.
E5,Orecchiette,Productos Secos,4.29,Italia,Pequeñas pastas con forma de orecchiette ideal...,NaN

In [17]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_Cliente   100 non-null    int64
 1   ID_Producto  100 non-null    object
 2   Fecha_Venta  100 non-null    object
 3   Cantidad     100 non-null    int64
 4   Total        100 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ KB

In [14]:
df_productos.isnull().sum()

ID                 0
Nombre_Producto    0
Categoría          0
Precio             0
Origen             0
Descripción        1
dtype: int64

In [10]:
df_clientes = pd.read_csv("../files/clientes.csv")
df_clientes.head()

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

In [15]:
df_clientes.isnull().sum()

id              0
first_name      0
last_name       0
email          27
gender         77
City          124
Country       154
Address        41
dtype: int64

In [ ]:
df_clientes